{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "\n",
    "import nest_asyncio\n",
    "nest_asyncio.apply()\n",
    "\n",
    "OPENAI_API_KEY = os.getenv(\"OPENAI_API_KEY\")\n",
    "os.environ[\"OPENAI_API_KEY\"] = OPENAI_API_KEY"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# load the documents\n",
    "from llama_index.core import SimpleDirectoryReader\n",
    "\n",
    "documents = SimpleDirectoryReader(\"data/Trump/\").load_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from llama_index.core import VectorStoreIndex, SimpleDirectoryReader\n",
    "from llama_index.core.settings import Settings\n",
    "\n",
    "vector_index = VectorStoreIndex.from_documents(documents)\n",
    "\n",
    "query_engine = vector_index.as_query_engine()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "GENERATOR_LLM = \"gpt-3.5-turbo\"\n",
    "CRITIC_LLM = \"gpt-3.5-turbo\"\n",
    "EVALUATOR_LLM = \"gpt-3.5-turbo\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "from llama_index.llms.openai import OpenAI\n",
    "\n",
    "generator_llm = OpenAI(model=GENERATOR_LLM)\n",
    "critic_llm = OpenAI(model=CRITIC_LLM)\n",
    "evaluator_llm = OpenAI(model=EVALUATOR_LLM)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "EVALUATOR_EMBEDDING = \"text-embedding-ada-002\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from llama_index.embeddings.openai import OpenAIEmbedding\n",
    "\n",
    "evaluator_embedding = OpenAIEmbedding(model=EVALUATOR_EMBEDDING)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'documents' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mdocuments\u001b[49m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'documents' is not defined"
     ]
    }
   ],
   "source": [
    "documents"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pypdf in ./venv/lib/python3.11/site-packages (5.0.1)\n"
     ]
    }
   ],
   "source": [
    "! pip install pypdf"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "\n",
    "file_path = (\n",
    "    \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf\"\n",
    ")\n",
    "loader = PyPDFLoader(file_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "docs = loader.load()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "text_splitter = RecursiveCharacterTextSplitter(\n",
    "    chunk_size=512,\n",
    "    chunk_overlap=20,\n",
    "    length_function=len,\n",
    "    add_start_index=True,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "chunks = text_splitter.split_documents(docs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 0, 'start_index': 0}, page_content='FormerPresidentDonaldTrumpwasshotandinjuredinanassassinationattempton\\nSaturdaynightthatalsokilledaspectatorandcriticallyinjuredtwoothers.Sniperskilled\\ntheshooter,a20-year-oldman,afterhefiredeightroundsattherallyinButler,\\nPennsylvania.\\nTheformerpresidentcouldbeseentouchinghisearastheshootingunfoldedbeforehe\\nwasshieldedbySecretServiceandwhiskedoffstage—withbloodonhisface—and\\nintoanSUVtosafety.Trumpsaidinasocialmediapostthatabulletpiercedtheupper\\npartofhisrightear.'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 0, 'start_index': 448}, page_content='partofhisrightear.\\n\"IknewimmediatelythatsomethingwaswronginthatIheardawhizzingsound,shots,\\nandimmediatelyfeltthebulletrippingthroughtheskin,\"hesaid.\"Muchbleedingtook\\nplace,soIrealizedthenwhatwashappening.\"\\nTheSecretServicelatersaidTrumpwassafe,andthathewenttoalocalhospitalandleft\\nhourslater.\\nThegunmanwasfatallyshotbyaSecretServicesniper,authoritiessaid.\\nFBIofficialssaidtheshooterappearedtobealoneactor,andtheincidentwasbeing\\ninvestigatedasanassassinationattemptandasapotentialcaseofdomesticterrorism.'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 0, 'start_index': 952}, page_content=\"WhoshotDonaldTrump?\\nTheFBIidentifiedtheshooterearlySundayas20-year-oldThomasMatthewCrooks,of\\nBethelPark,Pennsylvania.ThetowninAlleghenyCounty,justoutsidePittsburgh,is\\nhometoabout30,000people.\\nLawenforcementofficialssayhewasarmedwithasemiautomaticAR-stylerifle.Law\\nenforcementsourcessaythegunwaslegallypurchasedin2013andregisteredtothe\\nshooter'sfather,MatthewCrooks.\\nCrookswasa2022graduateofBethelParkHighSchoolSchoolofficialspledgedto\\nworkwithlawenforcementinvestigatingtheshooting,andofferedcondolencestothose\"),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 0, 'start_index': 1463}, page_content='affectedbytheattack.\\nFormerclassmateJamesonMyers,amemberoftheschool\\'svarsityrifleteam,toldCBS\\nNewsthatCrookshadtriedoutfortheteamfreshmanyearbutdidnotmakethejunior\\nvarsityrosteranddidnotreturntotryoutfortheteaminsubsequentyears.\\nHecalledCrooksa\"nicekidwhonevertalkedpoorlyofanyone,\"adding,\"Ineverhave\\nthoughthimcapableofanythingI\\'veseenhimdointhelastfewdays.\"\\nAnotherclassmate,JasonKoehler,hadasomewhatdifferentview,tellingKDKA\\'sMegan\\nSchillerthatCrookswasalonerwhowasbulliedforhisappearanceandwore'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 1, 'start_index': 0}, page_content='camo/huntingoutfitsinclass.HesaidCrookswouldoftensitinthecafeteriaalonebefore\\nclass.HealsosaidCrookswasveryCOVID-consciousandworeasurgicalmasklong\\naftertheywererequired.\\nButMarkSigafoos,whograduatedwithCrooksandhadtwoclasseswithhimsenioryear,\\nsaidheneversawhimbullied.HedescribedCrooksassupersmartandapproachable,\\nengagedinclassandalwaysvolunteeringanswers.\\n\"Thisisoneofthethingsthatisbeingmisconstrued—hewasnotsometypeofloner\\ntrenchcoatwearer.AndIwillsayhewasdefinitelynerdy,forsure,buthenevergaveoff'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 1, 'start_index': 502}, page_content='thathewascreepyorlikeaschoolshooter,\"Sigafoossaid.\"Heseemedlikehewouldn\\'t\\nhurtafly.\"\\nCrooks\\'politicalleaningswerenotimmediatelyclear.HewasregisteredasaRepublican\\nvoterinPennsylvaniabutFederalElectionCommissionrecordsshowhepreviouslymade\\na$15donationtoaDemocratic-alignedgroup.\\nTherewasnoindicationthatCrookshadaconnectiontoanymilitarybranch,officials\\nconfirmedtoCBSNews.\\nCrookshadamembershipatanearbygunclubforatleastayear.BillSellitto,the'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 1, 'start_index': 942}, page_content=\"presidentoftheClairtonSportsmen'sClubinClairton,Pennsylvania,toldCBSNewsthat\\nCrookswasamember.\\nAlawenforcementofficialsaidearlySundaythattheSecretServiceandtheFBIare\\ninvestigatingthesuspect'sbackgroundandspeakingwithhisfamily.TheFBIhas\\nsecuredhishomeandfederallawenforcementissearchinghisfamily'sresidencein\\nsuburbanPittsburgh,thelawenforcementofficialsaid.Hisfamilyiscooperatingwith\\ninvestigators,anFBIofficialsaid.\\nLawenforcementsourcestoldCBSNewsonSundaythatsuspiciousdeviceswerefound\"),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 1, 'start_index': 1430}, page_content='inthegunman\\'svehicle.Thegunmanalsohadwithhimapieceofcommerciallyavailable\\nequipmentthatappearedcapableofinitiatingthedevices.Bombtechnicianscalledto\\nthescenewereinvolvedinsecuringandinvestigatingthedevices.\\nDoweknowthemotivefortheassassinationattempt?\\nInanewsconferencelateSaturdaynight,KevinRojek,specialagentinchargeoftheFBI\\nPittsburghoffice,refusedtospeculateonapossiblemotive.\\n\"Rightnow,we\\'retrackingdownallleads,anddoingallinterviews,andtrackinganything'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 1, 'start_index': 1889}, page_content='thatwecanregardingsuspiciouslocations,vehicles...that\\'sallrelatedtothisevent,but\\nIcan\\'tconfirmordenyanythingbeyondthat,\"Rojeksaid.\\nAlawenforcementofficialsaidnoforeignterrorismtieswereknownandthesuspectwas'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 2, 'start_index': 0}, page_content='notontheradaroflawenforcement.\\nTheFBIsaysinvestigatorsarecombingthroughhissocialmediapostingsandemails,\\nbutthatsofartheyhavefoundnothingtoleadthemtoamotive.Theysaidarenotseeing\\nanythingthreateninginhispostingssofar.\\nInvestigatorsalsohaveaccessedhiscellphone,whichwassenttotheFBIlabin\\nQuantico,Virginia,foranalysis.\\nTheFBIisleadingtheinvestigation,withassistancefromtheSecretServiceandstate\\nandlocalagencies.\\nHowisTrumpnow?\\nTheTrumpcampaignsaidinastatementSaturdaynightthattheformerpresidentwas'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 2, 'start_index': 494}, page_content='\\'fine.\"Hewastakentoalocalhospitalandleftafewhourslater.\\nInapostonTruthSocialSaturdaynight,Trumpdescribedhisinjuries:\"Iwasshotwitha\\nbulletthatpiercedtheupperpartofmyrightear.Iknewimmediatelythatsomethingwas\\nwronginthatIheardawhizzingsound,shots,andimmediatelyfeltthebulletripping\\nthroughtheskin.Muchbleedingtookplace,soIrealizedthenwhatwashappening.GOD\\nBLESSAMERICA!\"\\nHethankedtheSecretServiceandotherlawenforcementagenciesfortheirrapid\\nresponse,andextendedcondolencestothefamilyofthemanwhowaskilled.'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 2, 'start_index': 994}, page_content='HepostedonTruthSocialearlySundaythatAmericansneedto\"remainresilientinour\\nFaithandDefiantinthefaceofWickedness.\"\\n\"Inthismoment,itismoreimportantthaneverthatwestandUnited,andshowourTrue\\nCharacterasAmericans,remainingStrongandDetermined,andnotallowingEvilto\\nWin,\"Trumpwrote.\"ItrulyloveourCountry,andloveyouall,andlookforwardto\\nspeakingtoourGreatNationthisweekfromWisconsin,\"wheretheRepublicanNational\\nConventionbeginsMonday.\\nVideopostedbyaTrumpaidetosocialmediaearlySundaymorningshowedhimwalking'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 2, 'start_index': 1487}, page_content='downthestepsofhisplaneunaidedafterlandingatNewarkLibertyInternationalAirport\\ninNewJersey.\\nThefollowingday,hemadeanappearanceattheRepublicanNationalConventionin\\nMilwaukee,withhisrightearbandaged,andwasgreetedwithrousingcheersfromthe\\ncrowd.\\nWherewastheTrumprallyandhowfarawaywastheshooter?\\nTherallywasinButler,Pennsylvania,whichisnorthofPittsburghandisthecountyseat'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 3, 'start_index': 0}, page_content=\"ofButlerCounty.\\nThegunmanwasontheroofofabuilding,outsidetherally'ssecurityperimetersetupby\\ntheSecretService,andopenedfirefromabout410feetawayfromthestagewhere\\nTrumpwasspeaking,lawenforcementsourcessaid.\\nTwolawenforcementsourcestoldCBSNewsthattheshooterwasspottedoutsidethe\\nsecurityperimeteraspeoplewerefilingintotherally,andhewasreportedbyabystander\\ntotheButlerCountySheriff'sOffice.Hewasidentifiedasasuspiciouspersonbypolice,\\nthesourcessaid.Multipleattendeesalsosaidtheysawthegunmanandalertedofficers\"),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 3, 'start_index': 502}, page_content='shortlybeforetheshooting.\\nAnarmedmunicipalofficerwithButlerTownshipencounteredthegunmanbeforethe\\nshooting,ButlerCountySheriffMichaelSloupeconfirmedtoCBSNews.Theofficerand\\nothershadbeenpreviouslyalertedtoasuspiciouspersonandbegansearchingforhim\\nrightaway,SloupetoldCBSPittsburghreporterJenBorrasso.\\nAtsomepoint,theofficerwashoistedbyanotherofficerontotheroofofthebuilding\\nwheretheshooterwasinposition.Theshooterfocusedhisrifletowardstheofficer,who'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 3, 'start_index': 949}, page_content='letgoandfellofftheroof.Thentheshooterbeganfiringintothecrowd,accordingto\\nSloupe.\\nThegunmanfired6to8roundsusingasemiautomaticAR-styleriflefromhisposition\\napproximately400feetfromthepodium,beforehewasshotandkilledbyaSecret\\nServicesniperteam.\\nRojek,withtheFBI,calledit\"surprising\"thatthegunmanwasabletofiremultipleshots.\\n\"Itisincrediblydifficulttohaveavenueopentothepublic,andtosecurethatagainstany\\npossiblethreat,againstaverydeterminedattacker,\"PennsylvaniaStatePoliceLt.Col.'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 3, 'start_index': 1423}, page_content='GeorgeBivenssaidoftheSecretService.\"That\\'sahugelifttotryanddoit.\"\\nWhowasthevictimwhowasfatallyshot?\\nThespectatorwhowaskilledhasbeenidentifiedasCoreyComperatore,a50-year-old\\nmanwhowasshotwhileattemptingtoshieldhisfamilyfromthegunfire,Pennsylvania\\nGov.JoshShapirosaidatanewsconferenceSunday.\\n\"Coreywastheverybestofus,\"Shapirosaid.\"Coreydiedahero.Coreydoveonhis\\nfamilytoprotectthemlastnight.Coreywasa\\'girldad.\\'Coreywasafirefighter.Corey\\nwenttochurcheverySunday.Coreylovedhiscommunity.\"'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 3, 'start_index': 1906}, page_content='PennsylvaniaStateRep.MarciMustellocalledComperatore\"adevotedpublicservant,\\nhavingservedasthefirechiefforBuffaloTownshipFireCompany,andhewasa\\ncherishedmemberofourcommunityinButlerCounty.\"'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 4, 'start_index': 0}, page_content='\"Hiscommitmenttohiswifeandtwodaughters,andhisunwaveringdedicationtohis\\nroleasafirechiefexemplifiedhisremarkablecharacter,\"Mustellosaid.\"Myheartbreaks\\nforhislovedonesduringthisincrediblydifficulttime,andIjointhecommunityin\\nmourninghisloss.AtrueAmericanhero,Coreysacrificedhislifetoprotecthisfamily.\"\\n\"MayCoreyComperatore\\'smemorybeablessingandareminderoftheselflessservice\\nheprovidedtousall.\"\\nThetwospectatorswhowerewoundedhavebeenidentifiedas57-year-oldDavidDutch,'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 4, 'start_index': 464}, page_content='ofNewKensington,Pennsylvania,andJamesCopenhaver,74,ofMoonTownship,\\nPennsylvania.BothwerelistedincriticalbutstableconditionSunday.\\nWhatdidBidensayabouttheshooting?\\nPresidentBidenfirstrespondedtotheshootinginastatementsayinghewasgratefulto\\nhearthatTrumpwassafeanddoingwell.\\n\"JillandIaregratefultotheSecretServiceforgettinghimtosafety,\"hesaid.\"There\\'sno\\nplaceforthiskindofviolenceinAmerica.Wemustuniteasonenationtocondemnit.\"\\nHethenaddressedthenationshortlyafter8p.m.ETSaturday,saying\"thereisnoplace'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 4, 'start_index': 961}, page_content='forthiskindofviolenceinAmerica.\"\\n\"It\\'ssick.It\\'ssick,\"Mr.Bidensaid.\"It\\'soneofthereasonswhywehavetounitethis\\ncountry.Wecannotallowforthistobehappening.Wecannotbelikethis.Wecannot\\ncondonethis.\"\\nOnSunday,BidenmadebriefremarksattheWhiteHouse,sayinghewas\"sincerely\\ngrateful\"thatTrumpisdoingwell,addingthathespokewiththeformerpresidenton\\nSaturdaynight.Hecharacterizedthecallasa\"short,good\"conversation.\\nThepresidenthasbeengettingbriefedbytopofficialsandsaidhehasorderedan'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 4, 'start_index': 1426}, page_content='independentreviewofthesecurityandeventsatthePennsylvaniarallytodetermine\\nwhatwentwrong.\\n\"There\\'snoplaceinAmericaforthiskindofviolence,oranyviolenceforthatmatter,\"the\\npresidentsaid.\"Anassassinationattemptiscontrarytoeverythingwestandforasa\\nnation.It\\'snotwhoweareasanation.\"\\nThepresidentsaidunityisthe\"mostelusivegoalofall\"andaddedthat\"nothingismore\\nimportantthanthatrightnow.Unity.\"\\nABidencampaignofficialsaidSaturdaythatthecampaignwaspausingalloutbound'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 4, 'start_index': 1879}, page_content='communicationsandworkingtotakedowntheirtelevisionadsasquicklyaspossible.'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 5, 'start_index': 0}, page_content='–RobertCosta,PatMilton,AndyTriay,ArdenFarhi,FinGomez,AaronNavarro,Sara\\nCookandotherCBSNewsstaffcontributedreporting.')]"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "chunks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-821' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-820' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-826' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1360' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1359' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1656' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1657' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1662' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n"
     ]
    }
   ],
   "source": [
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "\n",
    "path = \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf\"\n",
    "loader = PyPDFLoader(path)\n",
    "docs = loader.load()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 0}, page_content='FormerPresidentDonaldTrumpwasshotandinjuredinanassassinationattempton\\nSaturdaynightthatalsokilledaspectatorandcriticallyinjuredtwoothers.Sniperskilled\\ntheshooter,a20-year-oldman,afterhefiredeightroundsattherallyinButler,\\nPennsylvania.\\nTheformerpresidentcouldbeseentouchinghisearastheshootingunfoldedbeforehe\\nwasshieldedbySecretServiceandwhiskedoffstage—withbloodonhisface—and\\nintoanSUVtosafety.Trumpsaidinasocialmediapostthatabulletpiercedtheupper\\npartofhisrightear.\\n\"IknewimmediatelythatsomethingwaswronginthatIheardawhizzingsound,shots,\\nandimmediatelyfeltthebulletrippingthroughtheskin,\"hesaid.\"Muchbleedingtook\\nplace,soIrealizedthenwhatwashappening.\"\\nTheSecretServicelatersaidTrumpwassafe,andthathewenttoalocalhospitalandleft\\nhourslater.\\nThegunmanwasfatallyshotbyaSecretServicesniper,authoritiessaid.\\nFBIofficialssaidtheshooterappearedtobealoneactor,andtheincidentwasbeing\\ninvestigatedasanassassinationattemptandasapotentialcaseofdomesticterrorism.\\nWhoshotDonaldTrump?\\nTheFBIidentifiedtheshooterearlySundayas20-year-oldThomasMatthewCrooks,of\\nBethelPark,Pennsylvania.ThetowninAlleghenyCounty,justoutsidePittsburgh,is\\nhometoabout30,000people.\\nLawenforcementofficialssayhewasarmedwithasemiautomaticAR-stylerifle.Law\\nenforcementsourcessaythegunwaslegallypurchasedin2013andregisteredtothe\\nshooter\\'sfather,MatthewCrooks.\\nCrookswasa2022graduateofBethelParkHighSchoolSchoolofficialspledgedto\\nworkwithlawenforcementinvestigatingtheshooting,andofferedcondolencestothose\\naffectedbytheattack.\\nFormerclassmateJamesonMyers,amemberoftheschool\\'svarsityrifleteam,toldCBS\\nNewsthatCrookshadtriedoutfortheteamfreshmanyearbutdidnotmakethejunior\\nvarsityrosteranddidnotreturntotryoutfortheteaminsubsequentyears.\\nHecalledCrooksa\"nicekidwhonevertalkedpoorlyofanyone,\"adding,\"Ineverhave\\nthoughthimcapableofanythingI\\'veseenhimdointhelastfewdays.\"\\nAnotherclassmate,JasonKoehler,hadasomewhatdifferentview,tellingKDKA\\'sMegan\\nSchillerthatCrookswasalonerwhowasbulliedforhisappearanceandwore'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 1}, page_content='camo/huntingoutfitsinclass.HesaidCrookswouldoftensitinthecafeteriaalonebefore\\nclass.HealsosaidCrookswasveryCOVID-consciousandworeasurgicalmasklong\\naftertheywererequired.\\nButMarkSigafoos,whograduatedwithCrooksandhadtwoclasseswithhimsenioryear,\\nsaidheneversawhimbullied.HedescribedCrooksassupersmartandapproachable,\\nengagedinclassandalwaysvolunteeringanswers.\\n\"Thisisoneofthethingsthatisbeingmisconstrued—hewasnotsometypeofloner\\ntrenchcoatwearer.AndIwillsayhewasdefinitelynerdy,forsure,buthenevergaveoff\\nthathewascreepyorlikeaschoolshooter,\"Sigafoossaid.\"Heseemedlikehewouldn\\'t\\nhurtafly.\"\\nCrooks\\'politicalleaningswerenotimmediatelyclear.HewasregisteredasaRepublican\\nvoterinPennsylvaniabutFederalElectionCommissionrecordsshowhepreviouslymade\\na$15donationtoaDemocratic-alignedgroup.\\nTherewasnoindicationthatCrookshadaconnectiontoanymilitarybranch,officials\\nconfirmedtoCBSNews.\\nCrookshadamembershipatanearbygunclubforatleastayear.BillSellitto,the\\npresidentoftheClairtonSportsmen\\'sClubinClairton,Pennsylvania,toldCBSNewsthat\\nCrookswasamember.\\nAlawenforcementofficialsaidearlySundaythattheSecretServiceandtheFBIare\\ninvestigatingthesuspect\\'sbackgroundandspeakingwithhisfamily.TheFBIhas\\nsecuredhishomeandfederallawenforcementissearchinghisfamily\\'sresidencein\\nsuburbanPittsburgh,thelawenforcementofficialsaid.Hisfamilyiscooperatingwith\\ninvestigators,anFBIofficialsaid.\\nLawenforcementsourcestoldCBSNewsonSundaythatsuspiciousdeviceswerefound\\ninthegunman\\'svehicle.Thegunmanalsohadwithhimapieceofcommerciallyavailable\\nequipmentthatappearedcapableofinitiatingthedevices.Bombtechnicianscalledto\\nthescenewereinvolvedinsecuringandinvestigatingthedevices.\\nDoweknowthemotivefortheassassinationattempt?\\nInanewsconferencelateSaturdaynight,KevinRojek,specialagentinchargeoftheFBI\\nPittsburghoffice,refusedtospeculateonapossiblemotive.\\n\"Rightnow,we\\'retrackingdownallleads,anddoingallinterviews,andtrackinganything\\nthatwecanregardingsuspiciouslocations,vehicles...that\\'sallrelatedtothisevent,but\\nIcan\\'tconfirmordenyanythingbeyondthat,\"Rojeksaid.\\nAlawenforcementofficialsaidnoforeignterrorismtieswereknownandthesuspectwas'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 2}, page_content='notontheradaroflawenforcement.\\nTheFBIsaysinvestigatorsarecombingthroughhissocialmediapostingsandemails,\\nbutthatsofartheyhavefoundnothingtoleadthemtoamotive.Theysaidarenotseeing\\nanythingthreateninginhispostingssofar.\\nInvestigatorsalsohaveaccessedhiscellphone,whichwassenttotheFBIlabin\\nQuantico,Virginia,foranalysis.\\nTheFBIisleadingtheinvestigation,withassistancefromtheSecretServiceandstate\\nandlocalagencies.\\nHowisTrumpnow?\\nTheTrumpcampaignsaidinastatementSaturdaynightthattheformerpresidentwas\\n\\'fine.\"Hewastakentoalocalhospitalandleftafewhourslater.\\nInapostonTruthSocialSaturdaynight,Trumpdescribedhisinjuries:\"Iwasshotwitha\\nbulletthatpiercedtheupperpartofmyrightear.Iknewimmediatelythatsomethingwas\\nwronginthatIheardawhizzingsound,shots,andimmediatelyfeltthebulletripping\\nthroughtheskin.Muchbleedingtookplace,soIrealizedthenwhatwashappening.GOD\\nBLESSAMERICA!\"\\nHethankedtheSecretServiceandotherlawenforcementagenciesfortheirrapid\\nresponse,andextendedcondolencestothefamilyofthemanwhowaskilled.\\nHepostedonTruthSocialearlySundaythatAmericansneedto\"remainresilientinour\\nFaithandDefiantinthefaceofWickedness.\"\\n\"Inthismoment,itismoreimportantthaneverthatwestandUnited,andshowourTrue\\nCharacterasAmericans,remainingStrongandDetermined,andnotallowingEvilto\\nWin,\"Trumpwrote.\"ItrulyloveourCountry,andloveyouall,andlookforwardto\\nspeakingtoourGreatNationthisweekfromWisconsin,\"wheretheRepublicanNational\\nConventionbeginsMonday.\\nVideopostedbyaTrumpaidetosocialmediaearlySundaymorningshowedhimwalking\\ndownthestepsofhisplaneunaidedafterlandingatNewarkLibertyInternationalAirport\\ninNewJersey.\\nThefollowingday,hemadeanappearanceattheRepublicanNationalConventionin\\nMilwaukee,withhisrightearbandaged,andwasgreetedwithrousingcheersfromthe\\ncrowd.\\nWherewastheTrumprallyandhowfarawaywastheshooter?\\nTherallywasinButler,Pennsylvania,whichisnorthofPittsburghandisthecountyseat'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 3}, page_content='ofButlerCounty.\\nThegunmanwasontheroofofabuilding,outsidetherally\\'ssecurityperimetersetupby\\ntheSecretService,andopenedfirefromabout410feetawayfromthestagewhere\\nTrumpwasspeaking,lawenforcementsourcessaid.\\nTwolawenforcementsourcestoldCBSNewsthattheshooterwasspottedoutsidethe\\nsecurityperimeteraspeoplewerefilingintotherally,andhewasreportedbyabystander\\ntotheButlerCountySheriff\\'sOffice.Hewasidentifiedasasuspiciouspersonbypolice,\\nthesourcessaid.Multipleattendeesalsosaidtheysawthegunmanandalertedofficers\\nshortlybeforetheshooting.\\nAnarmedmunicipalofficerwithButlerTownshipencounteredthegunmanbeforethe\\nshooting,ButlerCountySheriffMichaelSloupeconfirmedtoCBSNews.Theofficerand\\nothershadbeenpreviouslyalertedtoasuspiciouspersonandbegansearchingforhim\\nrightaway,SloupetoldCBSPittsburghreporterJenBorrasso.\\nAtsomepoint,theofficerwashoistedbyanotherofficerontotheroofofthebuilding\\nwheretheshooterwasinposition.Theshooterfocusedhisrifletowardstheofficer,who\\nletgoandfellofftheroof.Thentheshooterbeganfiringintothecrowd,accordingto\\nSloupe.\\nThegunmanfired6to8roundsusingasemiautomaticAR-styleriflefromhisposition\\napproximately400feetfromthepodium,beforehewasshotandkilledbyaSecret\\nServicesniperteam.\\nRojek,withtheFBI,calledit\"surprising\"thatthegunmanwasabletofiremultipleshots.\\n\"Itisincrediblydifficulttohaveavenueopentothepublic,andtosecurethatagainstany\\npossiblethreat,againstaverydeterminedattacker,\"PennsylvaniaStatePoliceLt.Col.\\nGeorgeBivenssaidoftheSecretService.\"That\\'sahugelifttotryanddoit.\"\\nWhowasthevictimwhowasfatallyshot?\\nThespectatorwhowaskilledhasbeenidentifiedasCoreyComperatore,a50-year-old\\nmanwhowasshotwhileattemptingtoshieldhisfamilyfromthegunfire,Pennsylvania\\nGov.JoshShapirosaidatanewsconferenceSunday.\\n\"Coreywastheverybestofus,\"Shapirosaid.\"Coreydiedahero.Coreydoveonhis\\nfamilytoprotectthemlastnight.Coreywasa\\'girldad.\\'Coreywasafirefighter.Corey\\nwenttochurcheverySunday.Coreylovedhiscommunity.\"\\nPennsylvaniaStateRep.MarciMustellocalledComperatore\"adevotedpublicservant,\\nhavingservedasthefirechiefforBuffaloTownshipFireCompany,andhewasa\\ncherishedmemberofourcommunityinButlerCounty.\"'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 4}, page_content='\"Hiscommitmenttohiswifeandtwodaughters,andhisunwaveringdedicationtohis\\nroleasafirechiefexemplifiedhisremarkablecharacter,\"Mustellosaid.\"Myheartbreaks\\nforhislovedonesduringthisincrediblydifficulttime,andIjointhecommunityin\\nmourninghisloss.AtrueAmericanhero,Coreysacrificedhislifetoprotecthisfamily.\"\\n\"MayCoreyComperatore\\'smemorybeablessingandareminderoftheselflessservice\\nheprovidedtousall.\"\\nThetwospectatorswhowerewoundedhavebeenidentifiedas57-year-oldDavidDutch,\\nofNewKensington,Pennsylvania,andJamesCopenhaver,74,ofMoonTownship,\\nPennsylvania.BothwerelistedincriticalbutstableconditionSunday.\\nWhatdidBidensayabouttheshooting?\\nPresidentBidenfirstrespondedtotheshootinginastatementsayinghewasgratefulto\\nhearthatTrumpwassafeanddoingwell.\\n\"JillandIaregratefultotheSecretServiceforgettinghimtosafety,\"hesaid.\"There\\'sno\\nplaceforthiskindofviolenceinAmerica.Wemustuniteasonenationtocondemnit.\"\\nHethenaddressedthenationshortlyafter8p.m.ETSaturday,saying\"thereisnoplace\\nforthiskindofviolenceinAmerica.\"\\n\"It\\'ssick.It\\'ssick,\"Mr.Bidensaid.\"It\\'soneofthereasonswhywehavetounitethis\\ncountry.Wecannotallowforthistobehappening.Wecannotbelikethis.Wecannot\\ncondonethis.\"\\nOnSunday,BidenmadebriefremarksattheWhiteHouse,sayinghewas\"sincerely\\ngrateful\"thatTrumpisdoingwell,addingthathespokewiththeformerpresidenton\\nSaturdaynight.Hecharacterizedthecallasa\"short,good\"conversation.\\nThepresidenthasbeengettingbriefedbytopofficialsandsaidhehasorderedan\\nindependentreviewofthesecurityandeventsatthePennsylvaniarallytodetermine\\nwhatwentwrong.\\n\"There\\'snoplaceinAmericaforthiskindofviolence,oranyviolenceforthatmatter,\"the\\npresidentsaid.\"Anassassinationattemptiscontrarytoeverythingwestandforasa\\nnation.It\\'snotwhoweareasanation.\"\\nThepresidentsaidunityisthe\"mostelusivegoalofall\"andaddedthat\"nothingismore\\nimportantthanthatrightnow.Unity.\"\\nABidencampaignofficialsaidSaturdaythatthecampaignwaspausingalloutbound\\ncommunicationsandworkingtotakedowntheirtelevisionadsasquicklyaspossible.'),\n",
       " Document(metadata={'source': '/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf', 'page': 5}, page_content='–RobertCosta,PatMilton,AndyTriay,ArdenFarhi,FinGomez,AaronNavarro,Sara\\nCookandotherCBSNewsstaffcontributedreporting.')]"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "docs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to /Users/chris/nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 52,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import nltk\n",
    "nltk.download('punkt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain_community.document_loaders import TextLoader\n",
    "from langchain.document_loaders import DirectoryLoader\n",
    "\n",
    "path = \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Sample_Docs_Markdown/\"\n",
    "loader = DirectoryLoader(path, glob=\"**/*.md\", loader_cls=TextLoader)\n",
    "docs = loader.load()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-821' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-820' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-826' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1360' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1359' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1656' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1657' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-1662' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=AttributeError(\"'OpenAI' object has no attribute 'generate'\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/pydantic/main.py\", line 856, in __getattr__\n",
      "    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')\n",
      "AttributeError: 'OpenAI' object has no attribute 'generate'\n"
     ]
    }
   ],
   "source": [
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "\n",
    "path = \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/data/Trump/Trump.pdf\"\n",
    "loader = PyPDFLoader(path)\n",
    "docs = loader.load()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ragas.llms import LangchainLLMWrapper\n",
    "from langchain_openai import ChatOpenAI\n",
    "evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model=\"gpt-4o\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain_openai import OpenAI\n",
    "generator_llm = OpenAI(model=\"gpt-3.5-turbo\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Applying [EmbeddingExtractor, KeyphrasesExtractor, TitleExtractor]:   0%|          | 1/204 [00:04<14:36,  4.32s/it]Task exception was never retrieved\n",
      "future: <Task finished name='Task-296' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=ValueError(\"Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 119, in _generate_scenarios\n",
      "    themes: t.List[Themes] = run_async_batch(\n",
      "                             ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 852, in generate\n",
      "    raise ValueError(msg)\n",
      "ValueError: Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-297' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=ValueError(\"Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py\", line 89, in generate_scenarios\n",
      "    scenarios = await self._generate_scenarios(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py\", line 263, in _generate_scenarios\n",
      "    common_concepts: t.List[Concepts] = run_async_batch(\n",
      "                                        ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 167, in run_async_batch\n",
      "    return executor.results()\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 146, in results\n",
      "    results = asyncio.run(_aresults())\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 30, in run\n",
      "    return loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
      "    return f.result()\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 141, in _aresults\n",
      "    r = await future\n",
      "        ^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 615, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py\", line 203, in result\n",
      "    raise self._exception.with_traceback(self._exception_tb)\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 852, in generate\n",
      "    raise ValueError(msg)\n",
      "ValueError: Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-302' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:34> exception=ValueError(\"Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.\")>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py\", line 277, in __step\n",
      "    result = coro.send(None)\n",
      "             ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 36, in sema_coro\n",
      "    return await coro\n",
      "           ^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 81, in wrapped_callable_async\n",
      "    raise e\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py\", line 78, in wrapped_callable_async\n",
      "    result = await callable(*args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 126, in generate\n",
      "    output_single = await self.generate_multiple(\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py\", line 181, in generate_multiple\n",
      "    resp = await llm.generate(\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"/Users/chris/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 852, in generate\n",
      "    raise ValueError(msg)\n",
      "ValueError: Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.\n",
      "Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]                                                          \n",
      "\u001b[A\n",
      "                                                           \r"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[15], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mragas\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtestset\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m TestsetGenerator\n\u001b[1;32m      3\u001b[0m generator \u001b[38;5;241m=\u001b[39m TestsetGenerator(llm\u001b[38;5;241m=\u001b[39mgenerator_llm)\n\u001b[0;32m----> 4\u001b[0m dataset \u001b[38;5;241m=\u001b[39m \u001b[43mgenerator\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgenerate_with_langchain_docs\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdocuments\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdocs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtestset_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/generate.py:92\u001b[0m, in \u001b[0;36mTestsetGenerator.generate_with_langchain_docs\u001b[0;34m(self, documents, testset_size, transforms, query_distribution, run_config, callbacks, with_debugging_logs, raise_exceptions)\u001b[0m\n\u001b[1;32m     89\u001b[0m apply_transforms(kg, transforms)\n\u001b[1;32m     90\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mknowledge_graph \u001b[38;5;241m=\u001b[39m kg\n\u001b[0;32m---> 92\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgenerate\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     93\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtestset_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtestset_size\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     94\u001b[0m \u001b[43m    \u001b[49m\u001b[43mquery_distribution\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mquery_distribution\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     95\u001b[0m \u001b[43m    \u001b[49m\u001b[43mrun_config\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrun_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     96\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallbacks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     97\u001b[0m \u001b[43m    \u001b[49m\u001b[43mwith_debugging_logs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mwith_debugging_logs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     98\u001b[0m \u001b[43m    \u001b[49m\u001b[43mraise_exceptions\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mraise_exceptions\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     99\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/generate.py:186\u001b[0m, in \u001b[0;36mTestsetGenerator.generate\u001b[0;34m(self, testset_size, query_distribution, run_config, callbacks, with_debugging_logs, raise_exceptions)\u001b[0m\n\u001b[1;32m    183\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i, (scenario, _) \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(query_distribution):\n\u001b[1;32m    184\u001b[0m     exec\u001b[38;5;241m.\u001b[39msubmit(scenario\u001b[38;5;241m.\u001b[39mgenerate_scenarios, splits[i], \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mknowledge_graph)\n\u001b[0;32m--> 186\u001b[0m scenario_sample_list: t\u001b[38;5;241m.\u001b[39mList[t\u001b[38;5;241m.\u001b[39mList[BaseScenario]] \u001b[38;5;241m=\u001b[39m \u001b[43mexec\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresults\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    187\u001b[0m scenario_generation_rm\u001b[38;5;241m.\u001b[39mon_chain_end(\n\u001b[1;32m    188\u001b[0m     outputs\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mscenario_sample_list\u001b[39m\u001b[38;5;124m\"\u001b[39m: scenario_sample_list}\n\u001b[1;32m    189\u001b[0m )\n\u001b[1;32m    191\u001b[0m \u001b[38;5;66;03m# new group for Generation of Samples\u001b[39;00m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:146\u001b[0m, in \u001b[0;36mExecutor.results\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    142\u001b[0m         results\u001b[38;5;241m.\u001b[39mappend(r)\n\u001b[1;32m    144\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m results\n\u001b[0;32m--> 146\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43masyncio\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43m_aresults\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    147\u001b[0m sorted_results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28msorted\u001b[39m(results, key\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mlambda\u001b[39;00m x: x[\u001b[38;5;241m0\u001b[39m])\n\u001b[1;32m    148\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m [r[\u001b[38;5;241m1\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m sorted_results]\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py:30\u001b[0m, in \u001b[0;36m_patch_asyncio.<locals>.run\u001b[0;34m(main, debug)\u001b[0m\n\u001b[1;32m     28\u001b[0m task \u001b[38;5;241m=\u001b[39m asyncio\u001b[38;5;241m.\u001b[39mensure_future(main)\n\u001b[1;32m     29\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 30\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mloop\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_until_complete\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtask\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     31\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     32\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m task\u001b[38;5;241m.\u001b[39mdone():\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py:98\u001b[0m, in \u001b[0;36m_patch_loop.<locals>.run_until_complete\u001b[0;34m(self, future)\u001b[0m\n\u001b[1;32m     95\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m f\u001b[38;5;241m.\u001b[39mdone():\n\u001b[1;32m     96\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[1;32m     97\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mEvent loop stopped before Future completed.\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 98\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py:203\u001b[0m, in \u001b[0;36mFuture.result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    201\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__log_traceback \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m    202\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m--> 203\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception\u001b[38;5;241m.\u001b[39mwith_traceback(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception_tb)\n\u001b[1;32m    204\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_result\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py:277\u001b[0m, in \u001b[0;36mTask.__step\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    273\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    274\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    275\u001b[0m         \u001b[38;5;66;03m# We use the `send` method directly, because coroutines\u001b[39;00m\n\u001b[1;32m    276\u001b[0m         \u001b[38;5;66;03m# don't have `__iter__` and `__next__` methods.\u001b[39;00m\n\u001b[0;32m--> 277\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39msend(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m    278\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    279\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39mthrow(exc)\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:141\u001b[0m, in \u001b[0;36mExecutor.results.<locals>._aresults\u001b[0;34m()\u001b[0m\n\u001b[1;32m    132\u001b[0m results \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m    133\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m future \u001b[38;5;129;01min\u001b[39;00m tqdm(\n\u001b[1;32m    134\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m futures_as_they_finish,\n\u001b[1;32m    135\u001b[0m     desc\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdesc,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    139\u001b[0m     disable\u001b[38;5;241m=\u001b[39m\u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mshow_progress,\n\u001b[1;32m    140\u001b[0m ):\n\u001b[0;32m--> 141\u001b[0m     r \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m future\n\u001b[1;32m    142\u001b[0m     results\u001b[38;5;241m.\u001b[39mappend(r)\n\u001b[1;32m    144\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m results\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py:615\u001b[0m, in \u001b[0;36mas_completed.<locals>._wait_for_one\u001b[0;34m()\u001b[0m\n\u001b[1;32m    612\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m f \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    613\u001b[0m     \u001b[38;5;66;03m# Dummy value from _on_timeout().\u001b[39;00m\n\u001b[1;32m    614\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exceptions\u001b[38;5;241m.\u001b[39mTimeoutError\n\u001b[0;32m--> 615\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py:203\u001b[0m, in \u001b[0;36mFuture.result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    201\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__log_traceback \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m    202\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m--> 203\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception\u001b[38;5;241m.\u001b[39mwith_traceback(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception_tb)\n\u001b[1;32m    204\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_result\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py:277\u001b[0m, in \u001b[0;36mTask.__step\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    273\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    274\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    275\u001b[0m         \u001b[38;5;66;03m# We use the `send` method directly, because coroutines\u001b[39;00m\n\u001b[1;32m    276\u001b[0m         \u001b[38;5;66;03m# don't have `__iter__` and `__next__` methods.\u001b[39;00m\n\u001b[0;32m--> 277\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39msend(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m    278\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    279\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39mthrow(exc)\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:36\u001b[0m, in \u001b[0;36mas_completed.<locals>.sema_coro\u001b[0;34m(coro)\u001b[0m\n\u001b[1;32m     34\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21msema_coro\u001b[39m(coro):\n\u001b[1;32m     35\u001b[0m     \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m semaphore:\n\u001b[0;32m---> 36\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m coro\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:81\u001b[0m, in \u001b[0;36mExecutor.wrap_callable_with_index.<locals>.wrapped_callable_async\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     79\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     80\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mraise_exceptions:\n\u001b[0;32m---> 81\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m e\n\u001b[1;32m     82\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     83\u001b[0m         exec_name \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mtype\u001b[39m(e)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:78\u001b[0m, in \u001b[0;36mExecutor.wrap_callable_with_index.<locals>.wrapped_callable_async\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     76\u001b[0m result \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mnan\n\u001b[1;32m     77\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 78\u001b[0m     result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m     79\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     80\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mraise_exceptions:\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/base.py:89\u001b[0m, in \u001b[0;36mBaseSynthesizer.generate_scenarios\u001b[0;34m(self, n, knowledge_graph, callbacks)\u001b[0m\n\u001b[1;32m     83\u001b[0m callbacks \u001b[38;5;241m=\u001b[39m callbacks \u001b[38;5;129;01mor\u001b[39;00m []\n\u001b[1;32m     84\u001b[0m scenario_generation_rm, scenario_generation_group \u001b[38;5;241m=\u001b[39m new_group(\n\u001b[1;32m     85\u001b[0m     name\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mname,\n\u001b[1;32m     86\u001b[0m     inputs\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mn\u001b[39m\u001b[38;5;124m\"\u001b[39m: n, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mknowledge_graph\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;28mstr\u001b[39m(knowledge_graph)},\n\u001b[1;32m     87\u001b[0m     callbacks\u001b[38;5;241m=\u001b[39mcallbacks,\n\u001b[1;32m     88\u001b[0m )\n\u001b[0;32m---> 89\u001b[0m scenarios \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_generate_scenarios(\n\u001b[1;32m     90\u001b[0m     n, knowledge_graph, scenario_generation_group\n\u001b[1;32m     91\u001b[0m )\n\u001b[1;32m     92\u001b[0m scenario_generation_rm\u001b[38;5;241m.\u001b[39mon_chain_end(outputs\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mscenarios\u001b[39m\u001b[38;5;124m\"\u001b[39m: scenarios})\n\u001b[1;32m     93\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m scenarios\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/testset/synthesizers/abstract_query.py:119\u001b[0m, in \u001b[0;36mAbstractQuerySynthesizer._generate_scenarios\u001b[0;34m(self, n, knowledge_graph, callbacks)\u001b[0m\n\u001b[1;32m    113\u001b[0m     summaries \u001b[38;5;241m=\u001b[39m Summaries(\n\u001b[1;32m    114\u001b[0m         summaries\u001b[38;5;241m=\u001b[39msummaries,\n\u001b[1;32m    115\u001b[0m         num_themes\u001b[38;5;241m=\u001b[39mnum_themes,\n\u001b[1;32m    116\u001b[0m     )\n\u001b[1;32m    117\u001b[0m     kw_list\u001b[38;5;241m.\u001b[39mappend({\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mdata\u001b[39m\u001b[38;5;124m\"\u001b[39m: summaries, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mllm\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mllm, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcallbacks\u001b[39m\u001b[38;5;124m\"\u001b[39m: callbacks})\n\u001b[0;32m--> 119\u001b[0m themes: t\u001b[38;5;241m.\u001b[39mList[Themes] \u001b[38;5;241m=\u001b[39m \u001b[43mrun_async_batch\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    120\u001b[0m \u001b[43m    \u001b[49m\u001b[43mdesc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mGenerating common themes\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    121\u001b[0m \u001b[43m    \u001b[49m\u001b[43mfunc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcommon_theme_prompt\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgenerate\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    122\u001b[0m \u001b[43m    \u001b[49m\u001b[43mkwargs_list\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mkw_list\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    123\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    125\u001b[0m \u001b[38;5;66;03m# sample clusters and themes to get num_clusters * num_themes\u001b[39;00m\n\u001b[1;32m    126\u001b[0m clusters_sampled \u001b[38;5;241m=\u001b[39m []\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:167\u001b[0m, in \u001b[0;36mrun_async_batch\u001b[0;34m(desc, func, kwargs_list)\u001b[0m\n\u001b[1;32m    164\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m kwargs \u001b[38;5;129;01min\u001b[39;00m kwargs_list:\n\u001b[1;32m    165\u001b[0m     executor\u001b[38;5;241m.\u001b[39msubmit(func, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m--> 167\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mexecutor\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresults\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:146\u001b[0m, in \u001b[0;36mExecutor.results\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    142\u001b[0m         results\u001b[38;5;241m.\u001b[39mappend(r)\n\u001b[1;32m    144\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m results\n\u001b[0;32m--> 146\u001b[0m results \u001b[38;5;241m=\u001b[39m \u001b[43masyncio\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43m_aresults\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    147\u001b[0m sorted_results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28msorted\u001b[39m(results, key\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mlambda\u001b[39;00m x: x[\u001b[38;5;241m0\u001b[39m])\n\u001b[1;32m    148\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m [r[\u001b[38;5;241m1\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m sorted_results]\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py:30\u001b[0m, in \u001b[0;36m_patch_asyncio.<locals>.run\u001b[0;34m(main, debug)\u001b[0m\n\u001b[1;32m     28\u001b[0m task \u001b[38;5;241m=\u001b[39m asyncio\u001b[38;5;241m.\u001b[39mensure_future(main)\n\u001b[1;32m     29\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 30\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mloop\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_until_complete\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtask\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     31\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     32\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m task\u001b[38;5;241m.\u001b[39mdone():\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/nest_asyncio.py:98\u001b[0m, in \u001b[0;36m_patch_loop.<locals>.run_until_complete\u001b[0;34m(self, future)\u001b[0m\n\u001b[1;32m     95\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m f\u001b[38;5;241m.\u001b[39mdone():\n\u001b[1;32m     96\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[1;32m     97\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mEvent loop stopped before Future completed.\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 98\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py:203\u001b[0m, in \u001b[0;36mFuture.result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    201\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__log_traceback \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m    202\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m--> 203\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception\u001b[38;5;241m.\u001b[39mwith_traceback(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception_tb)\n\u001b[1;32m    204\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_result\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py:277\u001b[0m, in \u001b[0;36mTask.__step\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    273\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    274\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    275\u001b[0m         \u001b[38;5;66;03m# We use the `send` method directly, because coroutines\u001b[39;00m\n\u001b[1;32m    276\u001b[0m         \u001b[38;5;66;03m# don't have `__iter__` and `__next__` methods.\u001b[39;00m\n\u001b[0;32m--> 277\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39msend(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m    278\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    279\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39mthrow(exc)\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:141\u001b[0m, in \u001b[0;36mExecutor.results.<locals>._aresults\u001b[0;34m()\u001b[0m\n\u001b[1;32m    132\u001b[0m results \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m    133\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m future \u001b[38;5;129;01min\u001b[39;00m tqdm(\n\u001b[1;32m    134\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m futures_as_they_finish,\n\u001b[1;32m    135\u001b[0m     desc\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdesc,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    139\u001b[0m     disable\u001b[38;5;241m=\u001b[39m\u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mshow_progress,\n\u001b[1;32m    140\u001b[0m ):\n\u001b[0;32m--> 141\u001b[0m     r \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m future\n\u001b[1;32m    142\u001b[0m     results\u001b[38;5;241m.\u001b[39mappend(r)\n\u001b[1;32m    144\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m results\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py:615\u001b[0m, in \u001b[0;36mas_completed.<locals>._wait_for_one\u001b[0;34m()\u001b[0m\n\u001b[1;32m    612\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m f \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    613\u001b[0m     \u001b[38;5;66;03m# Dummy value from _on_timeout().\u001b[39;00m\n\u001b[1;32m    614\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exceptions\u001b[38;5;241m.\u001b[39mTimeoutError\n\u001b[0;32m--> 615\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/futures.py:203\u001b[0m, in \u001b[0;36mFuture.result\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    201\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__log_traceback \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m    202\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m--> 203\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception\u001b[38;5;241m.\u001b[39mwith_traceback(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_exception_tb)\n\u001b[1;32m    204\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_result\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/asyncio/tasks.py:277\u001b[0m, in \u001b[0;36mTask.__step\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    273\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    274\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    275\u001b[0m         \u001b[38;5;66;03m# We use the `send` method directly, because coroutines\u001b[39;00m\n\u001b[1;32m    276\u001b[0m         \u001b[38;5;66;03m# don't have `__iter__` and `__next__` methods.\u001b[39;00m\n\u001b[0;32m--> 277\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39msend(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m    278\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    279\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39mthrow(exc)\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:36\u001b[0m, in \u001b[0;36mas_completed.<locals>.sema_coro\u001b[0;34m(coro)\u001b[0m\n\u001b[1;32m     34\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21msema_coro\u001b[39m(coro):\n\u001b[1;32m     35\u001b[0m     \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m semaphore:\n\u001b[0;32m---> 36\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m coro\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:81\u001b[0m, in \u001b[0;36mExecutor.wrap_callable_with_index.<locals>.wrapped_callable_async\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     79\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     80\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mraise_exceptions:\n\u001b[0;32m---> 81\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m e\n\u001b[1;32m     82\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     83\u001b[0m         exec_name \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mtype\u001b[39m(e)\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/executor.py:78\u001b[0m, in \u001b[0;36mExecutor.wrap_callable_with_index.<locals>.wrapped_callable_async\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     76\u001b[0m result \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mnan\n\u001b[1;32m     77\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 78\u001b[0m     result \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m     79\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     80\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mraise_exceptions:\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py:126\u001b[0m, in \u001b[0;36mPydanticPrompt.generate\u001b[0;34m(self, llm, data, temperature, stop, callbacks)\u001b[0m\n\u001b[1;32m    123\u001b[0m callbacks \u001b[38;5;241m=\u001b[39m callbacks \u001b[38;5;129;01mor\u001b[39;00m []\n\u001b[1;32m    125\u001b[0m \u001b[38;5;66;03m# this is just a special case of generate_multiple\u001b[39;00m\n\u001b[0;32m--> 126\u001b[0m output_single \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mgenerate_multiple(\n\u001b[1;32m    127\u001b[0m     llm\u001b[38;5;241m=\u001b[39mllm,\n\u001b[1;32m    128\u001b[0m     data\u001b[38;5;241m=\u001b[39mdata,\n\u001b[1;32m    129\u001b[0m     n\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1\u001b[39m,\n\u001b[1;32m    130\u001b[0m     temperature\u001b[38;5;241m=\u001b[39mtemperature,\n\u001b[1;32m    131\u001b[0m     stop\u001b[38;5;241m=\u001b[39mstop,\n\u001b[1;32m    132\u001b[0m     callbacks\u001b[38;5;241m=\u001b[39mcallbacks,\n\u001b[1;32m    133\u001b[0m )\n\u001b[1;32m    134\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m output_single[\u001b[38;5;241m0\u001b[39m]\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/ragas/prompt/pydantic_prompt.py:181\u001b[0m, in \u001b[0;36mPydanticPrompt.generate_multiple\u001b[0;34m(self, llm, data, n, temperature, stop, callbacks)\u001b[0m\n\u001b[1;32m    175\u001b[0m prompt_rm, prompt_cb \u001b[38;5;241m=\u001b[39m new_group(\n\u001b[1;32m    176\u001b[0m     name\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mname,\n\u001b[1;32m    177\u001b[0m     inputs\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mdata\u001b[39m\u001b[38;5;124m\"\u001b[39m: processed_data},\n\u001b[1;32m    178\u001b[0m     callbacks\u001b[38;5;241m=\u001b[39mcallbacks,\n\u001b[1;32m    179\u001b[0m )\n\u001b[1;32m    180\u001b[0m prompt_value \u001b[38;5;241m=\u001b[39m PromptValue(prompt_str\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mto_string(processed_data))\n\u001b[0;32m--> 181\u001b[0m resp \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[43mllm\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgenerate\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    182\u001b[0m \u001b[43m    \u001b[49m\u001b[43mprompt_value\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    183\u001b[0m \u001b[43m    \u001b[49m\u001b[43mn\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    184\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtemperature\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtemperature\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    185\u001b[0m \u001b[43m    \u001b[49m\u001b[43mstop\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstop\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    186\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mprompt_cb\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    187\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    189\u001b[0m output_models \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m    190\u001b[0m parser \u001b[38;5;241m=\u001b[39m RagasOutputParser(pydantic_object\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39moutput_model)\n",
      "File \u001b[0;32m~/Desktop/7980/CS7980_Capstone_RBCMuseum/evaluator/venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py:852\u001b[0m, in \u001b[0;36mBaseLLM.generate\u001b[0;34m(self, prompts, stop, callbacks, tags, metadata, run_name, run_id, **kwargs)\u001b[0m\n\u001b[1;32m    847\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(prompts, \u001b[38;5;28mlist\u001b[39m):\n\u001b[1;32m    848\u001b[0m     msg \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    849\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mArgument \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mprompts\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m is expected to be of type List[str], received\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    850\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m argument of type \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mtype\u001b[39m(prompts)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    851\u001b[0m     )\n\u001b[0;32m--> 852\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(msg)\n\u001b[1;32m    853\u001b[0m \u001b[38;5;66;03m# Create callback managers\u001b[39;00m\n\u001b[1;32m    854\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(metadata, \u001b[38;5;28mlist\u001b[39m):\n",
      "\u001b[0;31mValueError\u001b[0m: Argument 'prompts' is expected to be of type List[str], received argument of type <class 'ragas.llms.prompt.PromptValue'>."
     ]
    }
   ],
   "source": [
    "from ragas.testset import TestsetGenerator\n",
    "\n",
    "generator = TestsetGenerator(llm=generator_llm)\n",
    "dataset = generator.generate_with_langchain_docs(documents=docs, testset_size=5)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
